<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";

type Row = Record<string, any>;
const rows = ref<Row[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(""); const message = ref("");
const form = ref({ installationId: "", displayName: "", platform: "Windows", appVersion: "" });
async function load() { loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>("/sync/devices"); rows.value = Array.isArray(result) ? result as Row[] : []; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "设备列表加载失败"; } finally { loading.value = false; } }
async function register() { if (!form.value.installationId.trim() || !form.value.displayName.trim() || !form.value.platform.trim()) { error.value = "安装标识、设备名称和平台不能为空"; return; } saving.value = true; error.value = ""; message.value = ""; try { await http.post("/sync/devices", { data: { installationId: form.value.installationId.trim(), displayName: form.value.displayName.trim(), platform: form.value.platform.trim(), appVersion: form.value.appVersion.trim() || undefined } }); form.value = { installationId: "", displayName: "", platform: "Windows", appVersion: "" }; message.value = "设备已登记"; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "设备登记失败"; } finally { saving.value = false; } }
async function revoke(row: Row) { if (!row.id || !window.confirm(`确认撤销设备“${row.displayName || row.id}”吗？`)) return; try { await http.post(`/sync/devices/${row.id}/revoke`); message.value = "设备已撤销"; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "设备撤销失败"; } }
onMounted(load);
</script>
<template>
  <main class="p-4 md:p-6"><div class="flex items-start justify-between gap-4 mb-6"><div><h1 class="text-2xl font-semibold">同步设备</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">登记可参与 Drive 同步的设备；设备身份与同步绑定分开管理。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4" /><el-alert v-if="message" :title="message" type="success" show-icon :closable="false" class="mb-4" /><el-card shadow="never" class="mb-4"><template #header><span>登记设备</span></template><el-form inline @submit.prevent="register"><el-form-item label="安装标识" required><el-input v-model="form.installationId" placeholder="客户端安装 UUID" class="w-64" clearable /></el-form-item><el-form-item label="设备名称" required><el-input v-model="form.displayName" placeholder="我的电脑" class="w-48" /></el-form-item><el-form-item label="平台" required><el-input v-model="form.platform" placeholder="Windows / macOS / Linux" class="w-48" /></el-form-item><el-form-item label="应用版本"><el-input v-model="form.appVersion" placeholder="可选" class="w-36" /></el-form-item><el-button type="primary" :loading="saving" @click="register">登记</el-button></el-form></el-card><el-card shadow="never"><template #header><span>已登记设备</span></template><el-skeleton v-if="loading" :rows="5" animated /><el-empty v-else-if="!rows.length" description="暂无已登记设备" /><el-table v-else :data="rows" stripe><el-table-column prop="displayName" label="设备" min-width="180" /><el-table-column prop="installationId" label="安装标识" min-width="260" /><el-table-column prop="platform" label="平台" width="120" /><el-table-column prop="appVersion" label="应用版本" width="120" /><el-table-column prop="trustState" label="信任状态" width="120" /><el-table-column prop="registeredAt" label="登记时间" min-width="180" /><el-table-column label="操作" width="100"><template #default="scope"><el-button link type="danger" :disabled="scope.row.trustState === 'REVOKED'" @click="revoke(scope.row)">撤销</el-button></template></el-table-column></el-table></el-card></main>
</template>
