<script setup lang="ts">
import { onMounted, ref } from "vue";
import { http } from "@/utils/http";

type Row = Record<string, any>;
const deviceId = ref(""); const downloads = ref<Row[]>([]); const intentId = ref(""); const manifest = ref<Row | null>(null); const attachmentId = ref(""); const sizeBytes = ref(0); const sha256 = ref(""); const required = ref(true); const loading = ref(false); const saving = ref(false); const error = ref(""); const message = ref("");
async function load() { if (!deviceId.value.trim()) { error.value = "请输入 Device ID"; return; } loading.value = true; error.value = ""; try { const result = await http.get<unknown, unknown>(`/offline/downloads?deviceId=${encodeURIComponent(deviceId.value.trim())}`); downloads.value = Array.isArray(result) ? result as Row[] : []; if (!intentId.value && downloads.value[0]?.id) intentId.value = String(downloads.value[0].id); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "下载任务加载失败"; } finally { loading.value = false; } }
async function loadManifest() { if (!intentId.value) { manifest.value = null; return; } try { manifest.value = await http.get<unknown, unknown>(`/offline/downloads/${intentId.value}/manifest`) as Row; } catch (e: any) { manifest.value = null; if (e?.response?.status !== 404) error.value = e?.response?.data?.detail || e?.message || "Manifest 加载失败"; } }
async function createManifest() { if (!intentId.value || !attachmentId.value.trim()) { error.value = "请选择下载任务并填写 Attachment ID"; return; } saving.value = true; error.value = ""; message.value = ""; try { manifest.value = await http.post<unknown, unknown>(`/offline/downloads/${intentId.value}/manifest`, { data: { items: [{ attachmentId: attachmentId.value.trim(), sizeBytes: sizeBytes.value, sha256: sha256.value.trim() || undefined, required: required.value }] } }) as Row; message.value = "Manifest 已生成，客户端必须完成完整性校验后才能标记完成"; } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "Manifest 生成失败"; } finally { saving.value = false; } }
async function startVerification() { if (!intentId.value) { error.value = "请选择下载任务"; return; } saving.value = true; error.value = ""; message.value = ""; try { await http.request("patch", `/offline/downloads/${intentId.value}`, { data: { state: "VERIFYING" } }); message.value = "已进入完整性校验状态"; await load(); } catch (e: any) { error.value = e?.response?.data?.detail || e?.message || "进入校验失败"; } finally { saving.value = false; } }
onMounted(load);
</script>
<template>
  <main class="p-4 md:p-6"><div class="flex items-start justify-between gap-4 mb-6"><div><h1 class="text-2xl font-semibold">下载完整性</h1><p class="mt-1 text-[var(--el-text-color-secondary)]">用 Manifest 记录期望大小与 SHA-256；只有客户端完成校验后才能进入 COMPLETED。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" show-icon :closable="false" class="mb-4" /><el-alert v-if="message" :title="message" type="success" show-icon :closable="false" class="mb-4" /><el-card shadow="never" class="mb-4"><template #header><span>选择下载任务</span></template><div class="flex flex-wrap gap-3 items-end"><el-form-item label="Device ID" required><el-input v-model="deviceId" class="w-72" clearable /></el-form-item><el-form-item label="下载任务" required><el-select v-model="intentId" class="w-96" @change="loadManifest"><el-option v-for="item in downloads" :key="item.id" :label="`${item.resourceId} · ${item.state}`" :value="item.id" /></el-select></el-form-item><el-button type="primary" :loading="saving" @click="startVerification">进入完整性校验</el-button></div></el-card><el-card shadow="never" class="mb-4"><template #header><span>生成 Manifest</span></template><div class="flex flex-wrap gap-3 items-end"><el-form-item label="Attachment ID" required><el-input v-model="attachmentId" class="w-72" clearable /></el-form-item><el-form-item label="期望大小（Bytes）"><el-input-number v-model="sizeBytes" :min="0" class="w-52" /></el-form-item><el-form-item label="期望 SHA-256"><el-input v-model="sha256" class="w-96" clearable /></el-form-item><el-checkbox v-model="required">必需项</el-checkbox><el-button :loading="saving" @click="createManifest">生成 Manifest</el-button></div></el-card><el-card shadow="never"><template #header><span>当前 Manifest</span></template><el-empty v-if="!manifest" description="暂无 Manifest，请先选择任务并生成或读取" /><div v-else><p class="mb-3">Manifest {{ manifest.id }} · 版本 {{ manifest.version }} · 生成于 {{ manifest.generatedAt }}</p><el-table :data="manifest.items || []" stripe><el-table-column prop="attachmentId" label="Attachment" min-width="260" /><el-table-column prop="sizeBytes" label="期望大小" width="150" /><el-table-column prop="sha256" label="期望 SHA-256" min-width="320" /><el-table-column prop="required" label="必需" width="100" /></el-table></div></el-card></main>
</template>
